### PR TITLE
test branch

### PR DESCRIPTION
**Pull request by divya864**
This project is about Attrition-Analysis-and-Prediction is added

### CODE REVIEW

**Comment by dewmonday** [comment]
updates about the project

**Comment by dewmonday** [comment]
The project is updated

**Comment by dewmonday** [comment]
The file and the pdf is added

**Review by divya864 — COMMENTED** [review]
This contains updated project files

**Review by divya864 — COMMENTED** [review]
The employee attrition project is submitted

**Comment by dewmonday** [comment]
[Employee-Attrition&Prediction.pdf](https://github.com/user-attachments/files/15744608/Employee-Attrition.Prediction.pdf)

**Pull request closed without merging**
